bitbox: simplify writeout
thrumdev/nomt pull request #270
Opened 2024-08-14 15:35 UTC by gabriele-0201

2024-08-14 15:35 UTC, gabriele-0201 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/thrumdev/nomt/270?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#270** <a href="https://app.graphite.dev/github/pr/thrumdev/nomt/270?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#269** <a href="https://app.graphite.dev/github/pr/thrumdev/nomt/269?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @gabriele-0201 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-14 15:53 UTC, rphmeier commented on nomt/src/beatree/writeout.rs
> +    cx.ln_write_out.wait_fsync(&mut io);
seems better to dispatch the fsyncs at the same time and then handle the completions async.

for a follow-up.

2024-08-14 16:34 UTC, rphmeier requested changes
I'm a bit conflicted around this PR.

On one hand, it does simplify things and looks like it is more aggressive with pushing onto io_uring. On the other, it looks like actually handling any kind of io error is going to be nearly impossible and would require either adding something like the inboxes back or to encapsulate the logic within `fn recv`. The inbox approach was better for that. Likewise, any attempt to handle completions _while_ write submission is ongoing would require another refactor of this code.

User data on io requests/completions is useful!

Even though it's simpler in the sense that there's less code, it's more conceptually complicated. 

The only refactor that was needed IMO is to move completion polling out of the `run` functions and have each helper gain a `handle_completion` function. And to have the main `run` loop attempt to take a single completion on each iteration, so long as each `run` indicated it wasn't currently trying to submit anything / the completion queue was full.

2024-08-15 14:21 UTC, pepyakin commented
Agreed. Closing for now just to clean up the queue, but feel free to resurrect as soon as you come back @gabriele-0201.

2024-08-15 14:21 UTC, closed without merging